server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 解决单页面应用(SPA)路由 404 问题
        try_files $uri $uri/ /index.html;
    }

    # 将 /api 开头的请求代理到后端
    location /api/ {
        # 'ctrl-blog-server' 是 docker-compose 中的服务名
        proxy_pass http://ctrl-blog-server:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /captcha/ {
        proxy_pass http://ctrl-blog-server:8080;
        proxy_set_header Host $host;
    }
}